"""Bring a freshly cloned workspace up to a buildable state.

    python scripts/init_workspace.py
    python scripts/init_workspace.py --verify

This is what replaces new_workspace.py's copy-and-rewrite dance now that the
workspace lives in git: a clone already has the code, so the only thing left
to do is materialize the personal files that git deliberately does not track
(identity.toml, rules/00-canonical-profile.md, automation/sources.toml,
automation/.env, rules/slices/_facts.md) from their committed .example
counterparts, generate automation/build_settings.json from its template, and
create the runtime directories nothing checks in. Safe to re-run: every step
either no-ops on an already-satisfied workspace or reports what it did.

--verify does not set anything up; it reports what is still FILL IN, missing,
or broken, using the same checks the pipeline itself depends on (identity
loads, the build-settings hook path exists, the guard self-test passes).
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# (personal file, example it is created from) — never overwritten if present.
WRITE_IF_MISSING = (
    ("identity.toml", "identity.toml.example"),
    ("rules/00-canonical-profile.md", "rules/00-canonical-profile.example.md"),
    ("automation/sources.toml", "automation/sources.toml.example"),
    ("automation/.env", "automation/.env.example"),
)

FACTS_STUB = """# Facts slice — NOT YET GENERATED

This file is generated by the 12-workspace-init agent from
rules/00-canonical-profile.md. It must be written before the first build:
the writing and verification agents read this slice instead of the full
canonical profile to keep handoffs compact, so an unwritten stub here means
they have no facts to work from.

Run the 12-workspace-init agent (or regenerate this slice by hand from the
canonical profile) once rules/00-canonical-profile.md is real.
"""

RUNTIME_DIRS = (
    "automation/state",
    "automation/logs",
    "_tmp",
)


def _references(line: str, token: str) -> bool:
    """True if `line` still contains the literal `{{` template token.

    Kept as a helper (rather than an inline `in` check) so the "no braces
    survived the substitution" rule reads the same way at both call sites:
    once right after generation, once during --verify.
    """
    return token in line


def generate_build_settings() -> None:
    template_path = ROOT / "automation" / "build_settings.template.json"
    target_path = ROOT / "automation" / "build_settings.json"

    text = template_path.read_text(encoding="utf-8")
    generated = text.replace("{{WORKSPACE_ROOT}}", ROOT.as_posix())

    remaining = [line for line in generated.splitlines() if _references(line, "{{")]
    if remaining:
        raise RuntimeError(
            f"{target_path} would still contain unresolved template tokens:\n  "
            + "\n  ".join(remaining))

    if target_path.exists():
        existing = target_path.read_text(encoding="utf-8")
        if existing == generated:
            print("  automation/build_settings.json — up to date")
            return
        target_path.write_text(generated, encoding="utf-8")
        print("  automation/build_settings.json — overwritten (generated file; "
              "the template is the source of truth)")
        return

    target_path.write_text(generated, encoding="utf-8")
    print("  automation/build_settings.json — created")


def write_if_missing(rel_target: str, rel_example: str) -> None:
    target = ROOT / rel_target
    if target.exists():
        print(f"  {rel_target} — exists, kept")
        return
    example = ROOT / rel_example
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(example.read_text(encoding="utf-8"), encoding="utf-8")
    print(f"  {rel_target} — created from {rel_example}")


def write_facts_stub() -> None:
    target = ROOT / "rules" / "slices" / "_facts.md"
    if target.exists():
        print("  rules/slices/_facts.md — exists, kept")
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(FACTS_STUB, encoding="utf-8")
    print("  rules/slices/_facts.md — created (stub)")


def make_runtime_dirs() -> None:
    for rel in RUNTIME_DIRS:
        target = ROOT / rel
        if target.exists():
            continue
        target.mkdir(parents=True, exist_ok=True)
        print(f"  {rel} — created")


def print_checklist() -> None:
    print("\nBefore the first build:")
    print("  1. identity.toml            — replace every FILL IN")
    print("  2. rules/00-canonical-profile.md — write the real profile, or run")
    print("                                 the 12-workspace-init agent to draft")
    print("                                 both this and identity.toml from your CV")
    print("  3. master/LaTeX/images/     — add photo.jpg and signature.png")
    print("  4. python -m venv automation/.venv")
    print("     automation/.venv/Scripts/pip install -r automation/requirements.txt")
    print("     automation/.venv/Scripts/playwright install chromium")
    print("  5. automation/.env          — a NEW Telegram bot token from")
    print("                                 BotFather, never a shared one")
    print("  6. automation/config.toml   — offset interval_minutes if another")
    print("                                 install polls the same boards")
    print("\nThen verify:")
    print("  python scripts/init_workspace.py --verify")


def run_setup() -> int:
    print("Generating automation/build_settings.json:")
    generate_build_settings()

    print("\nWriting personal files from examples:")
    for rel_target, rel_example in WRITE_IF_MISSING:
        write_if_missing(rel_target, rel_example)
    write_facts_stub()

    print("\nCreating runtime directories:")
    make_runtime_dirs()

    print_checklist()
    return 0


def run_verify() -> int:
    ok = True

    # (a) identity.toml loads and is fully filled in.
    sys.path.insert(0, str(ROOT / "scripts"))
    import workspace_identity  # noqa: E402  (path must be set first)

    print("[identity]")
    try:
        ident = workspace_identity.load()
        print(f"  OK — {ident.full_name} ({ident.doc_name('CV', '.pdf')})")
    except Exception as exc:  # noqa: BLE001 — report verbatim, do not narrow
        print(f"  FAIL — {exc}")
        ok = False

    # (b) build_settings.json exists and is fully substituted.
    print("[build_settings.json]")
    settings_path = ROOT / "automation" / "build_settings.json"
    hook_python: Path | None = None
    if not settings_path.exists():
        print("  FAIL — missing; run: python scripts/init_workspace.py")
        ok = False
    else:
        text = settings_path.read_text(encoding="utf-8")
        if "{{" in text:
            print("  FAIL — still contains an unresolved {{ token")
            ok = False
        else:
            print("  OK — no unresolved template tokens")
            import json
            hooks = json.loads(text).get("hooks", {}).get("PreToolUse", [])
            if hooks:
                hook_python = Path(hooks[0]["hooks"][0]["command"])

    # (c) the hook's python interpreter exists on disk — warn only.
    print("[build guard interpreter]")
    if hook_python is None:
        print("  WARN — could not read hook command from build_settings.json")
    elif not hook_python.exists():
        print(f"  WARN — {hook_python} does not exist yet "
              "(run: python -m venv automation/.venv)")
    else:
        print(f"  OK — {hook_python}")

    # (d) guard self-test.
    print("[guard self-test]")
    guard_path = ROOT / "automation" / "hooks" / "guard.py"
    result = subprocess.run(
        [sys.executable, str(guard_path), "--self-test"],
        capture_output=True, text=True, cwd=ROOT,
    )
    output_lines = [line for line in result.stdout.splitlines() if line.strip()]
    last_line = output_lines[-1] if output_lines else "(no output)"
    print(f"  {last_line}")

    # (e) rules/slices/_facts.md exists and is not the stub.
    print("[rules/slices/_facts.md]")
    facts_path = ROOT / "rules" / "slices" / "_facts.md"
    if not facts_path.exists():
        print("  FAIL — missing; run: python scripts/init_workspace.py")
        ok = False
    elif facts_path.read_text(encoding="utf-8") == FACTS_STUB:
        print("  FAIL — still the generated stub; write it from "
              "rules/00-canonical-profile.md (12-workspace-init agent)")
        ok = False
    else:
        print("  OK — written")

    # (f) photo and signature — warn only.
    print("[master/LaTeX/images]")
    for name in ("photo.jpg", "signature.png"):
        image_path = ROOT / "master" / "LaTeX" / "images" / name
        if image_path.exists():
            print(f"  OK — {name}")
        else:
            print(f"  WARN — {name} missing")

    return 0 if ok else 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--verify", action="store_true",
                        help="report readiness instead of writing anything")
    args = parser.parse_args(argv)

    if args.verify:
        return run_verify()
    return run_setup()


if __name__ == "__main__":
    raise SystemExit(main())
